apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsinternal
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 50000
      targetPort: 50000
      nodePort: 32001
  selector:
    app: jenkins
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: slow
  hostPath:
    path: /Users/dwalton/jenkins-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  volumeName: jenkins-pv
---
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: derrickwalton/jenkins:2.150.2-1
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-pv
              mountPath: /var/lib/jenkins
      volumes:
        - name: jenkins-pv
          persistentVolumeClaim:
              claimName: jenkins-pv-claim

