pipeline {
  agent {
    label 'jenkins-slave'
  }

  environment {
    registryCredential = 'dockerhub'
    version = "SDK29-$BUILD_NUMBER"
  }

  stages {
    stage('Setup') {
      steps {
        checkout scm
      }
    }

    stage('Android BUILDENV Build process') {
      steps {
        script {
          android = docker.build(
            "derrickwalton/android:" + version,
            "-f ./container/android/Dockerfile --no-cache ."
          )
        }
      }
    }
  }

  post {
    failure {
      notifyBuild()
    }
    success {
      script {
        docker.withRegistry('', registryCredential) {
          android.push()
          android.push('latest')
        }
        lastChanges since: 'LAST_SUCCESSFUL_BUILD', format:'SIDE',matching: 'LINE'
      }
    }
  }
}

def notifyBuild () {
  def colorName = 'RED'
  def colorCode = '#FF0000'
  def channelName = '#jenkins_alerts'
  details = """FAILED: Job ${env.JOB_NAME} ${env.BUILD_NUMBER}
  Check console output at ${env.BUILD_URL}${env.JOB_NAME} ${env.BUILD_NUMBER}"""
  slackSend(color: colorCode, message: details, channel: channelName)
}
